{"uuid":"62e89797-6e30-4f2e-939a-5931c3eaa396","name":"Scenario Outline: The user is presented with error message for code with invalid syntax in tryEditor for Arrays in Python page","children":["58eb1b81-19ea-4e91-807b-d0d127c21780"],"befores":[{"name":"appHooks.Hooks.scenario(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673371670611,"stop":1673371670611}],"afters":[{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673371670615,"stop":1673371670615},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673371670907,"stop":1673371670907},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673371671065,"stop":1673371671065},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"169440de-c0c1-4b49-94d0-9ce3ccd0b6f2-attachment","type":"image/png"},{"name":"Myscreenshot","source":"4c534223-dc0b-4870-8dd9-bff5935ad88f-attachment"}],"parameters":[],"start":1673371671085,"stop":1673371687824}],"start":1673371670611,"stop":1673371687824}