{"uuid":"7915a27b-7a75-48f2-875b-56bd6cbba356","name":"Scenario Outline: The user is presented with error message for code with invalid syntax in tryEditor for Arrays in Python page","children":["10f064a5-0770-426a-9db4-f571c85620b4"],"befores":[{"name":"appHooks.Hooks.scenario(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673371474585,"stop":1673371474585}],"afters":[{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673371474595,"stop":1673371474595},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673371474846,"stop":1673371474846},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673371474982,"stop":1673371474982},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"183764f0-fded-4b42-9bcf-22613502357e-attachment","type":"image/png"},{"name":"Myscreenshot","source":"2689d7b3-f39f-4862-a662-90b952ce612a-attachment"}],"parameters":[],"start":1673371475012,"stop":1673371475300}],"start":1673371474585,"stop":1673371475300}