{"uuid":"c53a059d-d174-442f-9f07-aa3f8e9735ce","name":"Scenario Outline: The user is presented with error message for code with invalid syntax in tryEditor for Arrays in Python page","children":["799e5829-c115-46a7-ba02-a2c8fdbc1c12"],"befores":[{"name":"appHooks.Hooks.scenario(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673284094588,"stop":1673284094588}],"afters":[{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673284094588,"stop":1673284094588},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673284094859,"stop":1673284094859},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673284095001,"stop":1673284095001},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"e11a0d71-12c5-4d97-940d-ae8dd98c5a9b-attachment","type":"image/png"},{"name":"Myscreenshot","source":"d8832fe9-6e60-43ca-9e67-a7fa9f354974-attachment"}],"parameters":[],"start":1673284095012,"stop":1673284095296}],"start":1673284094588,"stop":1673284095296}