<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-S7F1L181" failures="7" tests="47" name="com.runner.Runner" time="191.210" errors="1" timestamp="2023-01-10T14:11:53 CST" skipped="0">
  <testcase classname="com.runner.Runner" name="runScenario" time="2.563"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.439"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.126"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.017"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.221"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.923"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.763"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.684">
    <failure message="Result do not match expected [submission success] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:161)
at ✽.The user should be presented with successful submission message(file:///C:/Users/xunee/eclipse-workspace-2022/DS-ALGO-/src/test/resources/features/5arrays.feature:130)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.105"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.754"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.828">
    <failure message="Result do not match expected [NameError: name &#039;hello&#039; is not defined on line 1] but found [NameError: name &#039;hello&#039; is not defined on line 10]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [NameError: name 'hello' is not defined on line 1] but found [NameError: name 'hello' is not defined on line 10]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_error_message_as(ArraysStepDef.java:188)
at ✽.The user should be presented with error message as "NameError: name 'hello' is not defined on line 1"(file:///C:/Users/xunee/eclipse-workspace-2022/DS-ALGO-/src/test/resources/features/5arrays.feature:180)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.251"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.516">
    <failure message="expected [please enter valid password format] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [please enter valid password format] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.stepDefinations.RegisterStepDef.user_should_get_enter_valid_input_error_message(RegisterStepDef.java:159)
at ✽.user should get enter valid input error message "please enter valid password format"(file:///C:/Users/xunee/eclipse-workspace-2022/DS-ALGO-/src/test/resources/features/2register.feature:89)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.030"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.845"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.784"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.296"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.631"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.944"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.069"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="7.151"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.625"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.510"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.638">
    <failure message="Result do not match expected [submission success] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:161)
at ✽.The user should be presented with successful submission message(file:///C:/Users/xunee/eclipse-workspace-2022/DS-ALGO-/src/test/resources/features/5arrays.feature:150)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.905"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.540"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.651"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.245">
    <failure message="Result do not match expected [submission success] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:161)
at ✽.The user should be presented with successful submission message(file:///C:/Users/xunee/eclipse-workspace-2022/DS-ALGO-/src/test/resources/features/5arrays.feature:110)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.838"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="12.743"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.616"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.736"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.621">
    <failure message="expected [password should contain atleast eight characters.] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password should contain atleast eight characters.] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.stepDefinations.RegisterStepDef.user_should_get_password_atleast_eight_char_error_message(RegisterStepDef.java:145)
at ✽.user should get password atleast eight char error message "password should contain atleast eight characters."(file:///C:/Users/xunee/eclipse-workspace-2022/DS-ALGO-/src/test/resources/features/2register.feature:81)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.653"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.977">
    <failure message="Result do not match expected [submission success] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:161)
at ✽.The user should be presented with successful submission message(file:///C:/Users/xunee/eclipse-workspace-2022/DS-ALGO-/src/test/resources/features/5arrays.feature:170)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="7.365"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.459"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="18.749"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="10.594"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.876"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.117"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.099"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.761"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.571">
    <error message="stale element reference: element is not attached to the page document
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#stale_element_reference
Build info: version: &#039;4.7.1&#039;, revision: &#039;c6795baf1a3&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;11.0.16.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [19297e521f1b60e70ca600cfee87144b, getElementText {id=6f7a6efd-8ac2-4d99-9c78-8453938babfd}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\xunee\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:62276}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62276/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (19297e521f1b60e70ca600cfee87144b)] -&gt; id: id_username]
Session ID: 19297e521f1b60e70ca600cfee87144b" type="org.openqa.selenium.StaleElementReferenceException">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#stale_element_reference
Build info: version: '4.7.1', revision: 'c6795baf1a3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.16.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [19297e521f1b60e70ca600cfee87144b, getElementText {id=6f7a6efd-8ac2-4d99-9c78-8453938babfd}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\xunee\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:62276}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62276/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (19297e521f1b60e70ca600cfee87144b)] -> id: id_username]
Session ID: 19297e521f1b60e70ca600cfee87144b
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:551)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:207)
at jdk.internal.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52)
at com.sun.proxy.$Proxy44.getText(Unknown Source)
at com.pageObjects.RegisterPage.validatecompare(RegisterPage.java:155)
at com.stepDefinations.RegisterStepDef.user_should_get_password_not_similar_to_username_error_message(RegisterStepDef.java:171)
at ✽.user should get password not similar to username error message "password can not be similar as username"(file:///C:/Users/xunee/eclipse-workspace-2022/DS-ALGO-/src/test/resources/features/2register.feature:98)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.045"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.867"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.469"/>
  <system-out/>
</testsuite> <!-- com.runner.Runner -->
